baseURL = "http://localhost:1313/"
title = "Varden"
theme = "LoveIt"
themesDir = "themes"
defaultContentLanguage = "zh-cn"
locale = "zh-CN"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = false
ignoreErrors = ["error-remote-getjson"]
ignoreLogs = ["warning-goldmark-raw-html"]

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$']]
    inline = [['$', '$']]

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    pre = "<i class='fa fa-home' aria-hidden='true'></i>"
    post = ""
    name = "HOME"
    url = "/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "posts"
    pre = "<i class='fa fa-book' aria-hidden='true'></i>"
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "gallery"
    pre = "<i class='fa fa-images' aria-hidden='true'></i>"
    post = ""
    name = "Album"
    url = "/gallery/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "favorites"
    pre = "<i class='fa fa-star' aria-hidden='true'></i>"
    post = ""
    name = "Favorites"
    url = "/favorites/"
    title = ""
  [[menu.main]]
    weight = 5
    identifier = "friends"
    pre = "<i class='fa fa-user-friends' aria-hidden='true'></i>"
    post = ""
    name = "Friends"
    url = "/friends/"
    title = ""
  [[menu.main]]
    weight = 6
    identifier = "about"
    pre = "<i class='fa fa-address-card' aria-hidden='true'></i>"
    post = ""
    name = "About"
    url = "/about/"
    title = ""

[params]
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  title = "Varden"
  description = "欢迎来到我的博客"
  images = [""]

  [params.author]
    name = "Varden"
    email = ""
    link = ""

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      name = "VARDEN'S BLOG"
      pre = ""
      post = ""
      logo = ""
      typeit = true

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = ""
      title = ""
      subtitle = "欢迎来到我的博客"
      typeit = false
      social = true
      disclaimer = ""

  [params.social]
    GitHub = ""
    Email = ""
    RSS = true

  [params.page]
    [params.page.toc]
      enable = true
      keepStatic = false
    [params.page.comment]
      enable = true
    [params.page.comment.giscus]
      enable = true
      repo = "varrdenn/myblog"
      repoId = "R_kgDOSzSANQ"
      category = "Announcements"
      categoryId = "DIC_kwDOSzSANc4C-qz6"
      mapping = "pathname"
      strict = "0"
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "bottom"
      lightTheme = "noborder_light"
      darkTheme = "noborder_gray"
      lang = "zh-CN"

    [params.page.math]
      enable = true
      inlineLeftDelimiter = "$"
      inlineRightDelimiter = "$"
      blockLeftDelimiter = "$$"
      blockRightDelimiter = "$$"

    [params.page.library]
      [params.page.library.css]
        animateCSS = true
      [params.page.library.js]
        customJS = "js/custom.js"
    [params.page.share]
      enable = false

  [params.footer]
    enable = true
    since = "2025"
    license = ""